name: Daily checks

on:
  schedule:
    # 14:00 UTC = 9:00 AM CDT. Change if you want a different time.
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    # ✅ make all secrets available to the scripts
    env:
      META_API_VERSION: ${{ secrets.META_API_VERSION }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      # set both in case code falls back to FB_TOKEN
      FB_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Meta test
        run: python scripts/test_meta.py

      - name: Notion test
        run: python scripts/test_notion.py

      - name: Slack test
        if: ${{ success() }}
        run: python scripts/test_slack.py

      - name: Notify Slack on failure
        if: ${{ failure() }}
        run: |
          python - <<'PY'
          import os, json, requests
          url = os.environ["SLACK_WEBHOOK_URL"]
          requests.post(url, data=json.dumps({"text": "❌ Daily checks failed. See Actions logs."}),
                        headers={"Content-Type":"application/json"}, timeout=20)
          PY